### ISSUE TITLE
What exactly does ModeCarving do?

### ISSUE THREAD

**Issue by CaledoniaProject** [0xrawsec/golang-evtx#34]
What exactly does ModeCarving do? Can you explain on that?

**Comment by qjerome** [comment]
Hey @CaledoniaProject,

Sorry for this late reply ... The carving mode is used to retrieve EVTX logs entries in unusual places like (memory dumps, disk images ...). In this mode, we search only for things looking like EVTX chunks and trying to parse it, we do not care about all the EVTX file format.

**Comment by CaledoniaProject** [comment]
Looks like a useful parameter to me.
